//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snoop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Snoop.Infrastructure.WINDOWPLACEMENT AppChooserWindowPlacement {
            get {
                return ((global::Snoop.Infrastructure.WINDOWPLACEMENT)(this["AppChooserWindowPlacement"]));
            }
            set {
                this["AppChooserWindowPlacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SetOwnerWindow {
            get {
                return ((bool)(this["SetOwnerWindow"]));
            }
            set {
                this["SetOwnerWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ask")]
        public global::Snoop.Data.MultipleAppDomainMode MultipleAppDomainMode {
            get {
                return ((global::Snoop.Data.MultipleAppDomainMode)(this["MultipleAppDomainMode"]));
            }
            set {
                this["MultipleAppDomainMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ask")]
        public global::Snoop.Data.MultipleDispatcherMode MultipleDispatcherMode {
            get {
                return ((global::Snoop.Data.MultipleDispatcherMode)(this["MultipleDispatcherMode"]));
            }
            set {
                this["MultipleDispatcherMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CTRL + WIN + ALT + F12")]
        public global::Snoop.Data.KeyGestureEx GlobalHotKey {
            get {
                return ((global::Snoop.Data.KeyGestureEx)(this["GlobalHotKey"]));
            }
            set {
                this["GlobalHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%path%")]
        public string ILSpyPath {
            get {
                return ((string)(this["ILSpyPath"]));
            }
            set {
                this["ILSpyPath"] = value;
            }
        }
    }
}
