//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snoop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<WINDOWPLACEMENT xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <length>44</length>
  <flags>0</flags>
  <showCmd>1</showCmd>
  <minPosition>
    <X>-1</X>
    <Y>-1</Y>
  </minPosition>
  <maxPosition>
    <X>-1</X>
    <Y>-1</Y>
  </maxPosition>
  <normalPosition>
    <Left>10</Left>
    <Top>10</Top>
    <Right>650</Right>
    <Bottom>490</Bottom>
  </normalPosition>
</WINDOWPLACEMENT>")]
		public Snoop.WINDOWPLACEMENT SnoopUIWindowPlacement
		{
            get {
				return ((Snoop.WINDOWPLACEMENT)(this["SnoopUIWindowPlacement"]));
            }
            set {
                this["SnoopUIWindowPlacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<WINDOWPLACEMENT xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <length>44</length>
  <flags>0</flags>
  <showCmd>1</showCmd>
  <minPosition>
    <X>-1</X>
    <Y>-1</Y>
  </minPosition>
  <maxPosition>
    <X>-1</X>
    <Y>-1</Y>
  </maxPosition>
  <normalPosition>
    <Left>10</Left>
    <Top>10</Top>
    <Right>541</Right>
    <Bottom>36</Bottom>
  </normalPosition>
</WINDOWPLACEMENT>
")]
        public Snoop.WINDOWPLACEMENT AppChooserWindowPlacement {
            get {
				return ((Snoop.WINDOWPLACEMENT)(this["AppChooserWindowPlacement"]));
            }
            set {
                this["AppChooserWindowPlacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<WINDOWPLACEMENT xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <length>44</length>
  <flags>0</flags>
  <showCmd>1</showCmd>
  <minPosition>
    <X>-1</X>
    <Y>-1</Y>
  </minPosition>
  <maxPosition>
    <X>-1</X>
    <Y>-1</Y>
  </maxPosition>
  <normalPosition>
    <Left>10</Left>
    <Top>10</Top>
    <Right>541</Right>
    <Bottom>36</Bottom>
  </normalPosition>
</WINDOWPLACEMENT>
")]
		public Snoop.WINDOWPLACEMENT ZoomerWindowPlacement
		{
            get {
				return ((Snoop.WINDOWPLACEMENT)(this["ZoomerWindowPlacement"]));
            }
            set {
                this["ZoomerWindowPlacement"] = value;
            }
        }
    }
}
