<Project>
  <Import Project="../Directory.build.props" />

  <PropertyGroup>
    <TargetFrameworks>$(SnoopTestHarnessTargetFrameworks)</TargetFrameworks>
    <OutputPath>$(MSBuildThisFileDirectory)\bin\$(MSBuildProjectName)\$(Configuration)\</OutputPath>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
</Project>