name: Qodana

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  qodana-scan:
    name: Qodana Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        with:
          upload-result: false
          args: --baseline,qodana.sarif.json
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
